# Generated by Django 3.1.5 on 2021-01-27 20:58

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('byline', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('author_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='byline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='disclosure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='headline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pitch',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='promo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='headline', unique_with=('publish_at',)),
        ),
        migrations.CreateModel(
            name='AuthorArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.author')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', through='articles.AuthorArticle', to='articles.Author'),
        ),
    ]
